//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Input/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""General"",
            ""id"": ""c3906fe5-10b9-4fc2-aefe-c0b88e5f8ca1"",
            ""actions"": [
                {
                    ""name"": ""MouseLeft"",
                    ""type"": ""Button"",
                    ""id"": ""cb4cccd3-628d-4618-a0d3-c0a4c0aebb87"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseRight"",
                    ""type"": ""Button"",
                    ""id"": ""13b1933f-5b07-4d12-8535-30613ebea7d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveCamera"",
                    ""type"": ""Button"",
                    ""id"": ""f2ae7a61-d107-466c-a813-77dba4caa0fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZoomCamera"",
                    ""type"": ""Value"",
                    ""id"": ""7277adef-09d0-4d39-91ac-8e656ecfa93c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""759cb708-80f3-4927-9a84-eb0c04d266ef"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""3afb48b9-8201-4559-a63e-1142dc745a28"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""acbab6f4-53ef-494f-8a12-7f82bd3f4607"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fd0fb2a-a78c-4ed9-9677-2b0960323b1f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""866c14da-9de2-41ba-bada-046b59af78de"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""196cfc97-ca86-429f-88c8-034bf3f8545f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""11bb063c-7ab2-486e-88bd-1178ba51736c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c93385a9-d83c-4c80-a3a2-844810db7c9a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ebdd1b31-b1d8-43f4-86a5-20c375a58b30"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""abc988d6-7dd8-447c-a041-96097e8c7168"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""99b476c7-611f-4b87-90c0-5954796d8c0e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""39a81f0f-ce8d-4ac9-9bee-ee3b64407624"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Gameplay"",
            ""id"": ""895b1729-41c3-43c0-a22b-c6b4352e2aa7"",
            ""actions"": [
                {
                    ""name"": ""F1"",
                    ""type"": ""Button"",
                    ""id"": ""e37f3578-565c-4a7b-a6f7-f48ae1b894bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F2"",
                    ""type"": ""Button"",
                    ""id"": ""e37a6f60-1c07-4ee1-a408-34ce77620659"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F3"",
                    ""type"": ""Button"",
                    ""id"": ""34312069-3b76-4f5f-a6a3-d0cf11aa08d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F4"",
                    ""type"": ""Button"",
                    ""id"": ""ff29e2cb-cbd4-4d9e-acd1-b7e9bb4ea18d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F5"",
                    ""type"": ""Button"",
                    ""id"": ""08783d7d-c45e-47ed-8728-69ec8a0f46c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F6"",
                    ""type"": ""Button"",
                    ""id"": ""bbb479f7-1b8e-4d56-96ba-77608cf51b8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F7"",
                    ""type"": ""Button"",
                    ""id"": ""eef62f08-953a-40ef-9cbe-01b2a5aed891"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F8"",
                    ""type"": ""Button"",
                    ""id"": ""690d7c8e-e776-485c-8bd7-d18efccc6aa5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""F9"",
                    ""type"": ""Button"",
                    ""id"": ""73cb0891-eb06-4d98-9ff8-2a350912037a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number_1"",
                    ""type"": ""Button"",
                    ""id"": ""f8bb344d-6380-4755-8739-3f4459baadbd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number_2"",
                    ""type"": ""Button"",
                    ""id"": ""6457d100-a3f9-41a3-82df-6b16c66772bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number_3"",
                    ""type"": ""Button"",
                    ""id"": ""d8eaf64f-0187-4c4f-8d7c-ff6a918e7bec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number_4"",
                    ""type"": ""Button"",
                    ""id"": ""4ad7b203-9cc2-4ac9-9e58-59e52d26c9fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number_5"",
                    ""type"": ""Button"",
                    ""id"": ""ab13c05c-3aab-495a-be9b-fac9bdf85887"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number_6"",
                    ""type"": ""Button"",
                    ""id"": ""e10b15c4-ba73-40d1-b5d0-3cfd28d96745"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Demolish"",
                    ""type"": ""Button"",
                    ""id"": ""22f9f1b3-89cf-4e5e-ab0b-fd5330463501"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shift"",
                    ""type"": ""Button"",
                    ""id"": ""5439f76a-b5d1-4a89-9943-11778222e3f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Control"",
                    ""type"": ""Button"",
                    ""id"": ""79a4b5cd-f420-40e8-9eda-1a07e2fbd115"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Alt"",
                    ""type"": ""Button"",
                    ""id"": ""d0c2d135-5970-47b5-8316-c0cc5809469b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""311eac41-bdbc-4a3a-87ee-de3164016dca"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72a43bf2-a97f-43b2-9f1b-09b2fb1e4422"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4418b64-9f64-4bd5-8591-d93327b42cc1"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ae0ce88-3cb9-46a1-bfe0-57e6ef2b5d3c"",
                    ""path"": ""<Keyboard>/f4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""834d0f2b-fd0c-4cd7-bf56-ab6185a1d6ee"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c730a7a0-4680-4e1f-b2ec-1a08c124cc9a"",
                    ""path"": ""<Keyboard>/f6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9da318be-0cd2-4238-bf6a-e01f5343fb6b"",
                    ""path"": ""<Keyboard>/f7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3291387-abbd-4919-a658-8a995355ed22"",
                    ""path"": ""<Keyboard>/f8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b7a18d0-253e-4edd-95fb-c2f84dd07914"",
                    ""path"": ""<Keyboard>/f9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""F9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9d295b0-6dae-402c-90e5-524947e1b53e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Number_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b3f2f98-8c4c-4899-a88f-2d3a7127ed39"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Number_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac47ff2f-b723-4087-b01b-3d8e96d1fe0b"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Number_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ff75e3da-2427-4504-aef8-d5dcfb2e464f"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Number_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ca3b5d5-89f5-414d-9917-e654b388fc2c"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Number_5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f0d9104-620e-4e30-a809-ad317ae55537"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Number_6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""623974cb-fb80-4cd7-ae09-6d1d74da38a2"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Demolish"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39eca3d6-09f3-4d37-8898-f35825f38b17"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e54afc4a-0819-410d-8fc0-c43f4c511815"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Control"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""753edd3e-3d56-4c6c-985b-a950c40eef8d"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Alt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // General
        m_General = asset.FindActionMap("General", throwIfNotFound: true);
        m_General_MouseLeft = m_General.FindAction("MouseLeft", throwIfNotFound: true);
        m_General_MouseRight = m_General.FindAction("MouseRight", throwIfNotFound: true);
        m_General_MoveCamera = m_General.FindAction("MoveCamera", throwIfNotFound: true);
        m_General_ZoomCamera = m_General.FindAction("ZoomCamera", throwIfNotFound: true);
        m_General_Move = m_General.FindAction("Move", throwIfNotFound: true);
        m_General_Escape = m_General.FindAction("Escape", throwIfNotFound: true);
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_F1 = m_Gameplay.FindAction("F1", throwIfNotFound: true);
        m_Gameplay_F2 = m_Gameplay.FindAction("F2", throwIfNotFound: true);
        m_Gameplay_F3 = m_Gameplay.FindAction("F3", throwIfNotFound: true);
        m_Gameplay_F4 = m_Gameplay.FindAction("F4", throwIfNotFound: true);
        m_Gameplay_F5 = m_Gameplay.FindAction("F5", throwIfNotFound: true);
        m_Gameplay_F6 = m_Gameplay.FindAction("F6", throwIfNotFound: true);
        m_Gameplay_F7 = m_Gameplay.FindAction("F7", throwIfNotFound: true);
        m_Gameplay_F8 = m_Gameplay.FindAction("F8", throwIfNotFound: true);
        m_Gameplay_F9 = m_Gameplay.FindAction("F9", throwIfNotFound: true);
        m_Gameplay_Number_1 = m_Gameplay.FindAction("Number_1", throwIfNotFound: true);
        m_Gameplay_Number_2 = m_Gameplay.FindAction("Number_2", throwIfNotFound: true);
        m_Gameplay_Number_3 = m_Gameplay.FindAction("Number_3", throwIfNotFound: true);
        m_Gameplay_Number_4 = m_Gameplay.FindAction("Number_4", throwIfNotFound: true);
        m_Gameplay_Number_5 = m_Gameplay.FindAction("Number_5", throwIfNotFound: true);
        m_Gameplay_Number_6 = m_Gameplay.FindAction("Number_6", throwIfNotFound: true);
        m_Gameplay_Demolish = m_Gameplay.FindAction("Demolish", throwIfNotFound: true);
        m_Gameplay_Shift = m_Gameplay.FindAction("Shift", throwIfNotFound: true);
        m_Gameplay_Control = m_Gameplay.FindAction("Control", throwIfNotFound: true);
        m_Gameplay_Alt = m_Gameplay.FindAction("Alt", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // General
    private readonly InputActionMap m_General;
    private List<IGeneralActions> m_GeneralActionsCallbackInterfaces = new List<IGeneralActions>();
    private readonly InputAction m_General_MouseLeft;
    private readonly InputAction m_General_MouseRight;
    private readonly InputAction m_General_MoveCamera;
    private readonly InputAction m_General_ZoomCamera;
    private readonly InputAction m_General_Move;
    private readonly InputAction m_General_Escape;
    public struct GeneralActions
    {
        private @InputActions m_Wrapper;
        public GeneralActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseLeft => m_Wrapper.m_General_MouseLeft;
        public InputAction @MouseRight => m_Wrapper.m_General_MouseRight;
        public InputAction @MoveCamera => m_Wrapper.m_General_MoveCamera;
        public InputAction @ZoomCamera => m_Wrapper.m_General_ZoomCamera;
        public InputAction @Move => m_Wrapper.m_General_Move;
        public InputAction @Escape => m_Wrapper.m_General_Escape;
        public InputActionMap Get() { return m_Wrapper.m_General; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GeneralActions set) { return set.Get(); }
        public void AddCallbacks(IGeneralActions instance)
        {
            if (instance == null || m_Wrapper.m_GeneralActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GeneralActionsCallbackInterfaces.Add(instance);
            @MouseLeft.started += instance.OnMouseLeft;
            @MouseLeft.performed += instance.OnMouseLeft;
            @MouseLeft.canceled += instance.OnMouseLeft;
            @MouseRight.started += instance.OnMouseRight;
            @MouseRight.performed += instance.OnMouseRight;
            @MouseRight.canceled += instance.OnMouseRight;
            @MoveCamera.started += instance.OnMoveCamera;
            @MoveCamera.performed += instance.OnMoveCamera;
            @MoveCamera.canceled += instance.OnMoveCamera;
            @ZoomCamera.started += instance.OnZoomCamera;
            @ZoomCamera.performed += instance.OnZoomCamera;
            @ZoomCamera.canceled += instance.OnZoomCamera;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Escape.started += instance.OnEscape;
            @Escape.performed += instance.OnEscape;
            @Escape.canceled += instance.OnEscape;
        }

        private void UnregisterCallbacks(IGeneralActions instance)
        {
            @MouseLeft.started -= instance.OnMouseLeft;
            @MouseLeft.performed -= instance.OnMouseLeft;
            @MouseLeft.canceled -= instance.OnMouseLeft;
            @MouseRight.started -= instance.OnMouseRight;
            @MouseRight.performed -= instance.OnMouseRight;
            @MouseRight.canceled -= instance.OnMouseRight;
            @MoveCamera.started -= instance.OnMoveCamera;
            @MoveCamera.performed -= instance.OnMoveCamera;
            @MoveCamera.canceled -= instance.OnMoveCamera;
            @ZoomCamera.started -= instance.OnZoomCamera;
            @ZoomCamera.performed -= instance.OnZoomCamera;
            @ZoomCamera.canceled -= instance.OnZoomCamera;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Escape.started -= instance.OnEscape;
            @Escape.performed -= instance.OnEscape;
            @Escape.canceled -= instance.OnEscape;
        }

        public void RemoveCallbacks(IGeneralActions instance)
        {
            if (m_Wrapper.m_GeneralActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGeneralActions instance)
        {
            foreach (var item in m_Wrapper.m_GeneralActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GeneralActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GeneralActions @General => new GeneralActions(this);

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private List<IGameplayActions> m_GameplayActionsCallbackInterfaces = new List<IGameplayActions>();
    private readonly InputAction m_Gameplay_F1;
    private readonly InputAction m_Gameplay_F2;
    private readonly InputAction m_Gameplay_F3;
    private readonly InputAction m_Gameplay_F4;
    private readonly InputAction m_Gameplay_F5;
    private readonly InputAction m_Gameplay_F6;
    private readonly InputAction m_Gameplay_F7;
    private readonly InputAction m_Gameplay_F8;
    private readonly InputAction m_Gameplay_F9;
    private readonly InputAction m_Gameplay_Number_1;
    private readonly InputAction m_Gameplay_Number_2;
    private readonly InputAction m_Gameplay_Number_3;
    private readonly InputAction m_Gameplay_Number_4;
    private readonly InputAction m_Gameplay_Number_5;
    private readonly InputAction m_Gameplay_Number_6;
    private readonly InputAction m_Gameplay_Demolish;
    private readonly InputAction m_Gameplay_Shift;
    private readonly InputAction m_Gameplay_Control;
    private readonly InputAction m_Gameplay_Alt;
    public struct GameplayActions
    {
        private @InputActions m_Wrapper;
        public GameplayActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @F1 => m_Wrapper.m_Gameplay_F1;
        public InputAction @F2 => m_Wrapper.m_Gameplay_F2;
        public InputAction @F3 => m_Wrapper.m_Gameplay_F3;
        public InputAction @F4 => m_Wrapper.m_Gameplay_F4;
        public InputAction @F5 => m_Wrapper.m_Gameplay_F5;
        public InputAction @F6 => m_Wrapper.m_Gameplay_F6;
        public InputAction @F7 => m_Wrapper.m_Gameplay_F7;
        public InputAction @F8 => m_Wrapper.m_Gameplay_F8;
        public InputAction @F9 => m_Wrapper.m_Gameplay_F9;
        public InputAction @Number_1 => m_Wrapper.m_Gameplay_Number_1;
        public InputAction @Number_2 => m_Wrapper.m_Gameplay_Number_2;
        public InputAction @Number_3 => m_Wrapper.m_Gameplay_Number_3;
        public InputAction @Number_4 => m_Wrapper.m_Gameplay_Number_4;
        public InputAction @Number_5 => m_Wrapper.m_Gameplay_Number_5;
        public InputAction @Number_6 => m_Wrapper.m_Gameplay_Number_6;
        public InputAction @Demolish => m_Wrapper.m_Gameplay_Demolish;
        public InputAction @Shift => m_Wrapper.m_Gameplay_Shift;
        public InputAction @Control => m_Wrapper.m_Gameplay_Control;
        public InputAction @Alt => m_Wrapper.m_Gameplay_Alt;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Add(instance);
            @F1.started += instance.OnF1;
            @F1.performed += instance.OnF1;
            @F1.canceled += instance.OnF1;
            @F2.started += instance.OnF2;
            @F2.performed += instance.OnF2;
            @F2.canceled += instance.OnF2;
            @F3.started += instance.OnF3;
            @F3.performed += instance.OnF3;
            @F3.canceled += instance.OnF3;
            @F4.started += instance.OnF4;
            @F4.performed += instance.OnF4;
            @F4.canceled += instance.OnF4;
            @F5.started += instance.OnF5;
            @F5.performed += instance.OnF5;
            @F5.canceled += instance.OnF5;
            @F6.started += instance.OnF6;
            @F6.performed += instance.OnF6;
            @F6.canceled += instance.OnF6;
            @F7.started += instance.OnF7;
            @F7.performed += instance.OnF7;
            @F7.canceled += instance.OnF7;
            @F8.started += instance.OnF8;
            @F8.performed += instance.OnF8;
            @F8.canceled += instance.OnF8;
            @F9.started += instance.OnF9;
            @F9.performed += instance.OnF9;
            @F9.canceled += instance.OnF9;
            @Number_1.started += instance.OnNumber_1;
            @Number_1.performed += instance.OnNumber_1;
            @Number_1.canceled += instance.OnNumber_1;
            @Number_2.started += instance.OnNumber_2;
            @Number_2.performed += instance.OnNumber_2;
            @Number_2.canceled += instance.OnNumber_2;
            @Number_3.started += instance.OnNumber_3;
            @Number_3.performed += instance.OnNumber_3;
            @Number_3.canceled += instance.OnNumber_3;
            @Number_4.started += instance.OnNumber_4;
            @Number_4.performed += instance.OnNumber_4;
            @Number_4.canceled += instance.OnNumber_4;
            @Number_5.started += instance.OnNumber_5;
            @Number_5.performed += instance.OnNumber_5;
            @Number_5.canceled += instance.OnNumber_5;
            @Number_6.started += instance.OnNumber_6;
            @Number_6.performed += instance.OnNumber_6;
            @Number_6.canceled += instance.OnNumber_6;
            @Demolish.started += instance.OnDemolish;
            @Demolish.performed += instance.OnDemolish;
            @Demolish.canceled += instance.OnDemolish;
            @Shift.started += instance.OnShift;
            @Shift.performed += instance.OnShift;
            @Shift.canceled += instance.OnShift;
            @Control.started += instance.OnControl;
            @Control.performed += instance.OnControl;
            @Control.canceled += instance.OnControl;
            @Alt.started += instance.OnAlt;
            @Alt.performed += instance.OnAlt;
            @Alt.canceled += instance.OnAlt;
        }

        private void UnregisterCallbacks(IGameplayActions instance)
        {
            @F1.started -= instance.OnF1;
            @F1.performed -= instance.OnF1;
            @F1.canceled -= instance.OnF1;
            @F2.started -= instance.OnF2;
            @F2.performed -= instance.OnF2;
            @F2.canceled -= instance.OnF2;
            @F3.started -= instance.OnF3;
            @F3.performed -= instance.OnF3;
            @F3.canceled -= instance.OnF3;
            @F4.started -= instance.OnF4;
            @F4.performed -= instance.OnF4;
            @F4.canceled -= instance.OnF4;
            @F5.started -= instance.OnF5;
            @F5.performed -= instance.OnF5;
            @F5.canceled -= instance.OnF5;
            @F6.started -= instance.OnF6;
            @F6.performed -= instance.OnF6;
            @F6.canceled -= instance.OnF6;
            @F7.started -= instance.OnF7;
            @F7.performed -= instance.OnF7;
            @F7.canceled -= instance.OnF7;
            @F8.started -= instance.OnF8;
            @F8.performed -= instance.OnF8;
            @F8.canceled -= instance.OnF8;
            @F9.started -= instance.OnF9;
            @F9.performed -= instance.OnF9;
            @F9.canceled -= instance.OnF9;
            @Number_1.started -= instance.OnNumber_1;
            @Number_1.performed -= instance.OnNumber_1;
            @Number_1.canceled -= instance.OnNumber_1;
            @Number_2.started -= instance.OnNumber_2;
            @Number_2.performed -= instance.OnNumber_2;
            @Number_2.canceled -= instance.OnNumber_2;
            @Number_3.started -= instance.OnNumber_3;
            @Number_3.performed -= instance.OnNumber_3;
            @Number_3.canceled -= instance.OnNumber_3;
            @Number_4.started -= instance.OnNumber_4;
            @Number_4.performed -= instance.OnNumber_4;
            @Number_4.canceled -= instance.OnNumber_4;
            @Number_5.started -= instance.OnNumber_5;
            @Number_5.performed -= instance.OnNumber_5;
            @Number_5.canceled -= instance.OnNumber_5;
            @Number_6.started -= instance.OnNumber_6;
            @Number_6.performed -= instance.OnNumber_6;
            @Number_6.canceled -= instance.OnNumber_6;
            @Demolish.started -= instance.OnDemolish;
            @Demolish.performed -= instance.OnDemolish;
            @Demolish.canceled -= instance.OnDemolish;
            @Shift.started -= instance.OnShift;
            @Shift.performed -= instance.OnShift;
            @Shift.canceled -= instance.OnShift;
            @Control.started -= instance.OnControl;
            @Control.performed -= instance.OnControl;
            @Control.canceled -= instance.OnControl;
            @Alt.started -= instance.OnAlt;
            @Alt.performed -= instance.OnAlt;
            @Alt.canceled -= instance.OnAlt;
        }

        public void RemoveCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGeneralActions
    {
        void OnMouseLeft(InputAction.CallbackContext context);
        void OnMouseRight(InputAction.CallbackContext context);
        void OnMoveCamera(InputAction.CallbackContext context);
        void OnZoomCamera(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
    public interface IGameplayActions
    {
        void OnF1(InputAction.CallbackContext context);
        void OnF2(InputAction.CallbackContext context);
        void OnF3(InputAction.CallbackContext context);
        void OnF4(InputAction.CallbackContext context);
        void OnF5(InputAction.CallbackContext context);
        void OnF6(InputAction.CallbackContext context);
        void OnF7(InputAction.CallbackContext context);
        void OnF8(InputAction.CallbackContext context);
        void OnF9(InputAction.CallbackContext context);
        void OnNumber_1(InputAction.CallbackContext context);
        void OnNumber_2(InputAction.CallbackContext context);
        void OnNumber_3(InputAction.CallbackContext context);
        void OnNumber_4(InputAction.CallbackContext context);
        void OnNumber_5(InputAction.CallbackContext context);
        void OnNumber_6(InputAction.CallbackContext context);
        void OnDemolish(InputAction.CallbackContext context);
        void OnShift(InputAction.CallbackContext context);
        void OnControl(InputAction.CallbackContext context);
        void OnAlt(InputAction.CallbackContext context);
    }
}
